# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
ar = np.zeros(10, dtype="int32")
ar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3. Create a vector with values ranging from 10 to 49

In [4]:
r = np.arange(10,50)
r

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [11]:
np.shape(r)

(40,)

5. Print the type of the previous array in question 3

In [12]:
type(r)

numpy.ndarray

6. Print the numpy version and the configuration


In [11]:
print(np.__version__)
print(np.show_config())


1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ikon/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/ikon/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ikon/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', '

7. Print the dimension of the array in question 3


In [10]:
r.ndim


1

8. Create a boolean array with all the True values

In [19]:
b= np.array([1,1,1,1,1])
b

array([1, 1, 1, 1, 1])

9. Create a two dimensional array




In [3]:
darray= np.array([[0,2,5],[3,7,9]])

darray.ndim

2

10. Create a three dimensional array



In [27]:
ddarray= np.array([[[0,2,5],[3,7,9],[6,8,1]]])
ddarray
ddarray.ndim

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [20]:
rev = np.arange(49,9, -1)
rev

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
ar1 = np.zeros(10, dtype="int32")
np.size(ar1)
ar1[4]=1
ar1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [16]:
idarray= np.identity(3, dtype="int32")
idarray.ndim
idarray

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [17]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.astype(np.float64)
x.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [19]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [22]:
arr1 > arr2
# arr1 < arr2
# arr1 == arr2 we can compare both matrices in either way

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [27]:
result = np.arange(0,10)
print(result[1],result[3],result[5],result[7],result[9])

1 3 5 7 9


18. Replace all odd numbers to -1 from previous array

In [30]:
result[1]=result[3]=result[5]=result[7]=result[9]= -1
result

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [31]:
arr = np.arange(10)
arr[5]=arr[6]=arr[7]=arr[8]= 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [91]:
arrd = np.array([[1, 2, 3],

                  [4, 5, 6], 

                  [7, 8, 9]])
arrd[0:4 , 0:1]=arrd[0:1,1:2]=arrd[2: ,1:2]=arrd[0:4, 2:]=1
arrd[1:2,1:2]=0
arrd

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [36]:
arr2d = np.array([[1, 2, 3],

                  [4, 5, 6], 

                  [7, 8, 9]])
arr2d[1,1]=12
arr2d


array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])---
Convert all the values of 1st array to 64


In [42]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0]=64
arr3d


array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [68]:
y=np.array([[0,1,2,3,4],[5,6,7,8,9]])

y[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [70]:
z=np.array([[0,1,2,3,4],[5,6,7,8,9]])
z[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [78]:
q=np.array([[0,1,2],[3,4,5],[7,8,9]])
q[0:2,2:]

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [97]:
f=np.arange(100).reshape(10,10)

print ("minimum value = {}".format(f.min()))
print ("maximum value = {}".format(f.max()))

minimum value = 0
maximum value = 99


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [83]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a==b)


[False  True False  True False  True False  True False False]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [102]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!="Will"]

array([[ 1.00728081,  0.58689091,  0.84194795,  1.52126331],
       [ 1.02246016,  0.0238837 , -0.86609336, -0.55883294],
       [-0.03922258,  1.76080354, -2.24197317,  1.63299048],
       [ 0.91360821,  0.28201534, -0.34068233,  0.0473324 ],
       [-2.38928058, -1.93902725, -2.84693334,  0.20452783]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [132]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[(names!="Will") & (names!="Joe")]

array([[-0.37826325, -2.17856435,  0.08936108,  0.25137577],
       [-1.55795557,  0.17182863,  0.49908941,  1.68576912]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [149]:
d= np.random.randn(1,15).reshape(5,3)
d

array([[ 0.16342162, -1.18514823, -0.2531281 ],
       [ 0.83183072, -1.55606295,  0.5787334 ],
       [ 0.69481865, -0.75865676, -0.2389297 ],
       [-0.80134923, -1.10178733, -0.02000411],
       [ 0.71737826,  1.28289306, -0.18483542]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [150]:
c=np.random.rand(1,16).reshape(2,2,4)
c

array([[[0.00806502, 0.59898471, 0.43456984, 0.96398123],
        [0.86462963, 0.87500938, 0.43305575, 0.02824066]],

       [[0.72584757, 0.0452872 , 0.50055142, 0.806154  ],
        [0.36962447, 0.82655858, 0.54265653, 0.97979198]]])

33. Swap axes of the array you created in Question 32

In [151]:
c.T

array([[[0.00806502, 0.72584757],
        [0.86462963, 0.36962447]],

       [[0.59898471, 0.0452872 ],
        [0.87500938, 0.82655858]],

       [[0.43456984, 0.50055142],
        [0.43305575, 0.54265653]],

       [[0.96398123, 0.806154  ],
        [0.02824066, 0.97979198]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [155]:
s= np.arange(10).reshape(2,5)
sq= np.sqrt(s)
sq

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [162]:
a = np.random.randn(12)

b = np.random.randn(12)

np.maximum(a,b)

array([-0.32009652,  0.50655137, -0.43284005,  0.77904496, -0.03051693,
        0.57706644,  0.19544364, -0.89269915,  1.27895549,  1.55999849,
        1.36087053,  1.31346547])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [178]:
a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [185]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray[0: , 1:2]=10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [187]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
# to find dot product number of columns of x must be equal to 
# number of columns of y. therefore, their dot product is not possible.

40. Generate a matrix of 20 random values and find its cumulative sum

In [189]:
cum = np.random.rand(20)
print(f"The Cumulative sum of array is {cum.cumsum()}")

The Cumulative sum of array is [ 0.64564116  1.30174605  1.33148919  2.11100571  2.95963967  3.91837576
  4.23491304  4.76985706  5.57812966  6.01235329  6.71427124  7.59838285
  8.45249948  9.22312993  9.82001009 10.27569841 10.95931464 11.13490951
 11.22012895 11.65433996]
