# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
import numpy as np
ard = np.array([0,1,2,3,4,5,6,7,8,9])
ard2 = ard.reshape(2,5)
ard2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [24]:
ar1= np.arange(10).reshape(2,5)
ar2= np.ones((10), dtype=int).reshape(2,5)
np.vstack((ar1,ar2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [25]:
np.hstack((ar1,ar2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [31]:
ar3= np.arange(10).reshape(2,5)
far3=ar3.flatten()
far3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [33]:
ar4= np.arange(15).reshape(3,5)
ravar4= ar4.ravel()
ravar4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [35]:
ar5=np.arange(15).reshape(5,3)
ar5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [37]:
ar6=np.arange(25).reshape(5,5)
ar6**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [39]:
ar7=np.arange(30).reshape(5,6)
print(f"The mean of the array is {ar7.mean()}")

The mean of the array is 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [41]:
print(f"Standard Deviation of the array is {ar7.std()}")

Standard Deviation of the array is 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [44]:
print(f"The Median of the array is {np.median(ar7)}")

The Median of the array is 14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [45]:
ar7.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [56]:
ar8=np.arange(1,17).reshape(4,4)
s = np.trace(ar8) 
print("Sum of diagonal elements of 4X4 matrix:", s) 
ar8

Sum of diagonal elements of 4X4 matrix: 34


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## Question:13

### Find the determinant of the previous array in Q12?

In [60]:
print(np.linalg.det(ar8)) 

4.7331654313261276e-30


## Question:14

### Find the 5th and 95th percentile of an array?

In [63]:
print(f"The  5th percentile of an array = {np.percentile(ar8,5)}")
print(f"The 95th percentile of an array = {np.percentile(ar8,95)}")

The  5th percentile of an array = 1.75
The 95th percentile of an array = 15.25


## Question:15

### How to find if a given array has any null values?

In [65]:
ar8[:]= np.nan # to find null values in an array we use numpy's NaN function.